# This file contains all available configuration options

# options for analysis running
run:
  # default concurrency is a available CPU number
  concurrency: 6

  # exit code when at least one issue was found, default is 1
  issues-exit-code: 1

  # include test files or not, default is true
  tests: false

# output configuration options
output:
  # colored-line-number|line-number|json|tab|checkstyle|code-climate|junit-xml|github-actions
  # default is "colored-line-number"
  format: colored-line-number

  # print lines of code with issue, default is true
  print-issued-lines: true

  # print linter name in the end of issue text, default is true
  print-linter-name: true

# all available settings of specific linters
linters-settings:
  funlen:
    lines: 100
    statements: 80

  nestif:
    # minimal complexity of if statements to report, 5 by default
    min-complexity: 4

  godot:
    # comments to be checked: `declarations`, `toplevel`, or `all`
    scope: declarations
    # check that each sentence starts with a capital letter
    capital: false

  gofmt:
    # simplify code: gofmt with `-s` option, true by default
    simplify: true

  misspell:
    # Correct spellings using locale preferences for US or UK.
    # Default is to use a neutral variety of English.
    # Setting locale to US will correct the British spelling of 'colour' to 'color'.
    locale: US

  whitespace:
    multi-if: true # Enforces newlines (or comments) after every multi-line if statement
    multi-func: true # Enforces newlines (or comments) after every multi-line function signature

  stylecheck:
    # Select the Go version to target. The default is '1.13'.
    go: "1.17"
    # https://staticcheck.io/docs/options#checks
    checks: ["all", "-ST1000", "-ST1003", "-ST1016", "-ST1021", "-ST1022"]

  revive:
    ignore-generated-header: true
    severity: warning
    rules:
      - name: atomic
      - name: unhandled-error
        arguments : ["fmt.Printf", "myFunction"]
      - name: unexported-return
      - name: error-naming
      - name: defer


linters:
  disable-all: true
  enable:
    - gocritic
    - gocyclo
    - godot
    - gofmt
    - govet
    - funlen
    - misspell
    - nestif
    - revive
    - staticcheck
    - stylecheck
    - whitespace
  fast: false


issues:
  # Independently from option `exclude` we use default exclude patterns,
  # it can be disabled by this option. To list all
  # excluded by default patterns execute `golangci-lint run --help`.
  # Default value for this option is true.
  exclude-use-default: false

  # The default value is false. If set to true exclude and exclude-rules
  # regular expressions become case sensitive.
  exclude-case-sensitive: false

  # Maximum issues count per one linter. Set to 0 to disable. Default is 50.
  max-issues-per-linter: 5

  # Maximum count of issues with the same text. Set to 0 to disable. Default is 3.
  max-same-issues: 1

  # Fix found issues (if it's supported by the linter)
  fix: false
