version: "3.8"

services:
  auth:
    container_name: auth
    build:
      context: ./
      dockerfile: ./docker/auth.Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      postgresql:
        condition: service_healthy
    restart: always
    volumes:
      - ./:/auth
    networks:
      - web_api

  postgresql:
    image: postgres:12-alpine
    container_name: postgesql
    ports:
      - "5432:5432"
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=121073
      - POSTGRES_DB=auth
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 5s
      timeout: 3s
      retries: 5 
      start_period: 1s
    networks:
      - web_api

  migrate:
    image: migrate/migrate
    volumes: 
      - ./migrations:/migrations
    command: ["-path", "/migrations/auth", "-database",  "postgres://postgres:121073@postgresql:5432/auth?sslmode=disable", "up", "1"]
    depends_on:
      postgresql:
        condition: service_healthy
    networks:
      - web_api

networks:
  web_api:
    driver: bridge
