Auth:
  JwtExpires: 15m
  JwtSecretKey: 8Zz5tw0Ionm3XPZZfN0NOml3z9FMfmpgXwovR9fp6ryDIoGRM8EPHAB6iHsc0fb

Server:
  Addr: :5000
  SwaggerUrl: auth/doc.json
  ReadTimeout: 10s
  WriteTimeout: 10s
  IdleTimeout: 60s

DB:
  Host: localhost
  Port: 5432
  User: postgres
  DbName: compresso
  Password: 121073
  Driver: pgx
