HTTP:
    Addr: :5000
    ReadTimeout: 10s
    WriteTimeout: 10s
    IdleTimeout: 60s
    Pprof: true
    Swagger: true
    SwaggerUrl: "http://127.0.0.1:5000/swagger/auth/doc.json"

DB:
  Host: localhost
  Port: 5432
  User: postgres
  DbName: compresso
  Password: 121073
  Driver: pgx

Auth:
  JwtExpires: 15m
  JwtSecretKey: 8Zz5tw0Ionm3XPZZfN0NOml3z9FMfmpgXwovR9fp6ryDIoGRM8EPHAB6iHsc0fb


