Auth:
  JwtExpires: 15m
  JwtSecretKey: 8Zz5tw0Ionm3XPZZfN0NOml3z9FMfmpgXwovR9fp6ryDIoGRM8EPHAB6iHsc0fb

Server:
  Addr: :5000
  PprofPort: :5555
  SwaggerUrl: doc.json
  ReadTimeout: 5s
  WriteTimeout: 5s
  IdleTimeout: 60s
