name: deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: deploy all services
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout code
        uses: actions/checkout@v2
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      -
        name: Build and push auth svc
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          file: docker/auth/Dockerfile
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/auth:latest
      -
        name: Build and push video api
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          file: docker/videoapi/Dockerfile
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/videosvc:latest
      -
        name: Build and push video svc
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          file: docker/videosvc/Dockerfile
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/videosvc:latest
