name: lint

on:
  pull_request:
    branches:
      - main
      - dev

jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout code
        uses: actions/checkout@v2
      -
        name: golangci-lint
        uses: golangci/golangci-lint-action@v2
